### ISSUE TITLE
Incorrect behaviour with bad import inside function

### ISSUE THREAD

**Issue by tolomea** [unimport/unimport#175]
So I had some code that essentially looked like this

    import bob
    
    def func():
        import bob
        bob.fred(1)
    
    def other_func():
        bob.fred(2)

Which is not good, but is valid.

I ran the stable version with `--remove --include-star-import --ignore-init --gitignore` and it removed the top level import, which left the code in an invalid state as now `bob` is not imported at the `bob.fred(2)` point.

**Comment by isidentical** [comment]
This shouldn't have happened, will take a look. Thanks for the report @tolomea!

**Comment by isidentical** [comment]
@tolomea I've just release 0.8.0 which disabled our current system for duplicate import elimination. We'll probably reintroduce it in the 1.0.0 rewrite (the codebase was in an ad-hoc shape, so we decided to rewrite all the major components with knowing the current requirements). Hopefully we will pull it off and it will offer a proper duplicate import elimination system. Thanks for your report! Please test it with the latest version and let us know whether it still is problematic or not
