### ISSUE TITLE
Misses that names are used in type hints

### ISSUE THREAD

**Issue by adamchainz** [unimport/unimport#176]
I had a module that used an import only for a type hint, like:

```python
from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from models import User

def something(user: User) -> ...:
```

And the import of `User` got removed by `unimport`. This makes both mypy and flake8 unhappy.

**Comment by isidentical** [comment]
Hey @adamchainz, can you share the exact python version you have with me? I tried to test it on 3.8+ and it seems to work
```
(.venv38) (Python 3.8.5+) [  8:37ÖS ]  [ isidentical@desktop:~/unimport(master✔) ]
 $ cat t.py
from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from models import User

def something(user: User) -> ...:
    pass
(.venv38) (Python 3.8.5+) [  8:37ÖS ]  [ isidentical@desktop:~/unimport(master✔) ]
 $ python -m unimport t.py
✨ Congratulations there is no unused import in your project. ✨
(.venv38) (Python 3.8.5+) [  8:38ÖS ]  [ isidentical@desktop:~/unimport(master✔) ]
 $ python -m unimport -d t.py
(.venv38) (Python 3.8.5+) [  8:38ÖS ]  [ isidentical@desktop:~/unimport(master✔) ]
```

**Comment by adamchainz** [comment]
Sorry, I shrunk the example incorrectly. Here's an actual example triggering the bug:

```python
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from models import User


def inner_func(self):
    from models import User

    ...


def type_hint_func(user: User):
    ...

```

It seems the inner import is incorrectly interpreted as applying to the outer context. Maybe a duplicate of #175.

**Comment by isidentical** [comment]
Yep, it seems really similar to #175. I'll try to look into both of these issues in the weekend, thanks for also letting us know!

**Comment by adamchainz** [comment]
Thanks for a useful tool, and having pre-commit ready to go.

**Comment by isidentical** [comment]
@adamchainz I've just release 0.8.0 which disabled our current system for duplicate import elimination. We'll probably reintroduce it in the 1.0.0 rewrite (the codebase was in an ad-hoc shape, so we decided to rewrite all the major components with knowing the current requirements). Hopefully we will pull it off and it will offer a proper duplicate import elimination system. Thanks for your report!

**Comment by adamchainz** [comment]
Ok great, thanks for the update, I will try unimport again 👍
